### ISSUE TITLE
Is it possible to increase the size of a token's heart display?

### ISSUE THREAD

**Issue by RickLongleyAS** [ClipplerBlood/icrpgme#12]
Is there a method for increasing the size of each token's heart display? I'm running Foundry VTT on a widescreen TV for an in-person session. Thus, the default sized hearts are hard to see.

**Comment by ClipplerBlood** [comment]
Yes! 
But I'm not really planning on making it a setting 😢 

If you want to do it for your own game is quite easy but you have to change a js file.

### Steps:
1. Go to the system folder, and go open the `module/icrpgme.js` file (windows: `\AppData\Local\FoundryVTT\Data\systems\icrpgme\module\icrpgme.js`)
2. Open the file with an editor, like visual studio code or something
3. Edit line 2586 and 2587 with your preferred values. If your editor doesn't have the lines, you can search for the following:
```js
    // Configure size and positioning
    const size = 16;
    const gap = 2;
```

4. Those values are the pixel size of the hearts and the gap between them. You can experiment with them and tune them to your liking. Haven't really tested it so I don't really know if it screws something (probably won't 😛)
5. After making changes, to see them in Foundry you have to reload the page (if you had an icrpg world already opened)


> ⚠️ ⚠️ ⚠️ 
**Those changes will be overwritten when the system updates, so keep this in mind!**
It's not that critical since the change is quite small and no update is planned for the near future, but it's better if you are informed about this 😅 

Let me know if you need any help! I'll leave the issue open so that others can find more easily how to patch the token heart size

**Comment by RickLongleyAS** [comment]
This solved the issue entirely! Thank you very much!
